### ISSUE TITLE
Onnx in Javascript

### ISSUE THREAD

**Issue by shilsircar** [breizhn/DTLN#10]
@breizhn I am experimenting with loading Onnx model in js like this and experiencing an error. Looks like something on the input to lstm4 is not correct. All the ops are supported in Onnx I checked like DropOut, Activation etc here https://github.com/microsoft/onnxjs/blob/master/docs/operators.md

Any ideas why ?

        async function loadDTLN_modelOnnx()
        {
          
            const model1 = new onnx.InferenceSession();
            const model2 = new onnx.InferenceSession();
            var output1 = await model1.loadModel("./model_1.onnx");
            var output2 = await model2.loadModel("./model_2.onnx")
         };

It throws an error:

graph.ts:313 Uncaught (in promise) Error: unrecognized input '' for node: lstm_4
    at t.buildGraph (graph.ts:313)
    at new t (graph.ts:139)
    at Object.from (graph.ts:77)
    at t.load (model.ts:25)
    at session.ts:85
    at t.event (instrument.ts:294)
    at e.initialize (session.ts:81)
    at e.<anonymous> (session.ts:63)
    at inference-session-impl.ts:16
    at Object.next (inference-session-impl.ts:16)

**Comment by breizhn** [comment]
Sadly I found this https://github.com/microsoft/onnxjs/issues/167

**Comment by shilsircar** [comment]
Ahh sigh !!! Tfjs it is then :)

**Comment by breizhn** [comment]
I read into the documentation and it should support lstms. I converted the model with right opset. Try this model:
[models.zip](https://github.com/breizhn/DTLN/files/4906634/models.zip)

Probably the keras2onnx converter uses by default a newer opset for converting the models as used by onnx.js. This model is converted with opset 7.

**Comment by shilsircar** [comment]
Tried the test model. No luck same error. 
I debugged the onnx model graph loading code. The issue seems to be an input to LSTM. The object it throws the exception on seems to be this:

attribute: (3) [t, t, t]
domain: ""
input: (8) ["lstm_4_X", "lstm_4_W", "lstm_4_R", "lstm_4_B", **""**, "lstm_4_initial_h", "lstm_4_initial_c", **""**]
name: "lstm_4"
opType: "LSTM"
output: (3) ["lstm_4_Y", "lstm_4_Y_h", "lstm_4_Y_c"]
__proto__: Object

Notice empty **""** in 5th and last position. This is what its complaining about.


By the way in looking through the docs for Onnx Javascript LSTM op is not supported in JavaScript ?
https://github.com/microsoft/onnxjs/blob/master/docs/operators.md

In the LSTM column of the doc I don't see it mentioned for any opset.

**Comment by breizhn** [comment]
Oh yeah, it looks like I skipped that when reading on my phone. Hopefully they integrate the support for lstms soon.

**Comment by rktalusani** [comment]
> Ahh sigh !!! Tfjs it is then :)

did you get this working with JS? Any pointers?
