### ISSUE TITLE
How to calculate those metrics in the DTLN paper?

### ISSUE THREAD

**Issue by sufeidechabei** [breizhn/DTLN#16]
Could you please share some code about calculating the metrics , like PESQ SI-SDR STOI score  in the DTLN paper .

**Comment by sufeidechabei** [comment]
Besides how do you evaluate the performance in realtime  speech enhancement track?

**Comment by breizhn** [comment]
Hi,

the objective metrics in the paper were calculated with Matlab. Sadly I can not share this scripts at the moment. I good solution in python is maybe https://github.com/aliutkus/speechmetrics .

The evaluation for the challenge were performed by Microsoft with this framework https://github.com/microsoft/P.808 on the Amazon Mechanical Turk.

**Comment by sufeidechabei** [comment]
Hi, breizhn, In pesq, is the  reference signal the output of the model? here are snippest of my code, the mean pesq is 3.06. I'm not sure whether the way to calculate pesq is right@breizhn
est, fs = sf.read("/data/www/project_speech/datanoreverb/clean/" +estfile)
denoised, fs = sf.read("/data/www/project_speech/datanoreverb/noisy/" + noisyfile)
pesq(est, denoised, fs)

**Comment by sufeidechabei** [comment]
I use est as the reference signal in this case. @breizhn

**Comment by sufeidechabei** [comment]
Why I get the mean PESQ is 3.68 which is much higher than the result, when I use the PESQ(clean, estimation, samplerate).@breizhn

**Comment by breizhn** [comment]
Hi,

the reference signal is always the clean signal, so in the case of this model, the speech signal without noise. If the clean signal is not available, PESQ can not be used . 3.06 does not sound far from the result calculated in the paper.

**Comment by sufeidechabei** [comment]
thank you!

**Comment by schmiph2** [comment]
> Hi,
> 
> the objective metrics in the paper were calculated with Matlab. Sadly I can not share this scripts at the moment. I good solution in python is maybe https://github.com/aliutkus/speechmetrics .
> 
> The evaluation for the challenge were performed by Microsoft with this framework https://github.com/microsoft/P.808 on the Amazon Mechanical Turk.

I just stumbled across this issue.  For your information: I reimplemented most of these metrics in Python (see [pyspem](https://github.com/schmiph2/pysepm) )
