### ISSUE TITLE
How to run on Raspberry Pi?

### ISSUE THREAD

**Issue by guojunmin** [breizhn/DTLN#17]
Hi Nils, I'm trying to run your model on Raspberry Pi, however it seems miniconda doesn't support python3.7 yet. Should I degrade to python3.6 or install packages manually? Thanks.

**Comment by breizhn** [comment]
Hi,

yes conda does not work properly on an RaspberryPi. If you would like to use Tensorflow itself to run the model, install Tensorflow into a pyenv virtualenv. To run the quantized TF-lite model just download the TF-lite runtime and install it directly without an env. The links to the download-sides are also available in the README. The Python version does not matter so much.

**Comment by guojunmin** [comment]
Thanks a lot, I'll try both of them right away.
