### ISSUE TITLE
Any tricks to improve DTLN performance on Raspberry?

### ISSUE THREAD

**Issue by sufeidechabei** [breizhn/DTLN#18]
I test the real_time_audio_device.py, when there are two human voices in a environment, I want to extract one from the mixed speech, but the performance is not good, any tricks to improve this?

**Comment by breizhn** [comment]
The model is trained to only extract speech from non speech. If you would like to separate speech from speech you have train a network to do so. A possibility would be to first remove the noise with the DTLN and afterwards use a speaker separation approach to separate the speakers. At the moment I don't have a real-time speaker separation system available for distribution.
