### ISSUE TITLE
some error after python run_training.py

### ISSUE THREAD

**Issue by dttlgotv** [breizhn/DTLN#21]
Traceback (most recent call last):
  File "run_training.py", line 56, in <module>
    path_to_val_mix, path_to_val_speech)
  File "/data1/dtln/DTLN/DTLN_model.py", line 555, in train_model
    self.fs, train_flag=True)
  File "/data1/dtln/DTLN/DTLN_model.py", line 54, in __init__
    self.count_samples()
  File "/data1/dtln/DTLN/DTLN_model.py", line 68, in count_samples
    info = WavInfoReader(os.path.join(self.path_to_input, file))
  File "/root/.conda/envs/train_env/lib/python3.7/site-packages/wavinfo/wave_reader.py", line 52, in __init__
    self.main_list = chunks.children
AttributeError: 'ChunkDescriptor' object has no attribute 'children'

**Comment by dttlgotv** [comment]
> 
> 
> Traceback (most recent call last):
> File "run_training.py", line 56, in
> path_to_val_mix, path_to_val_speech)
> File "/data1/dtln/DTLN/DTLN_model.py", line 555, in train_model
> self.fs, train_flag=True)
> File "/data1/dtln/DTLN/DTLN_model.py", line 54, in **init**
> self.count_samples()
> File "/data1/dtln/DTLN/DTLN_model.py", line 68, in count_samples
> info = WavInfoReader(os.path.join(self.path_to_input, file))
> File "/root/.conda/envs/train_env/lib/python3.7/site-packages/wavinfo/wave_reader.py", line 52, in **init**
> self.main_list = chunks.children
> AttributeError: 'ChunkDescriptor' object has no attribute 'children'

@

> 
> 
> Traceback (most recent call last):
> File "run_training.py", line 56, in
> path_to_val_mix, path_to_val_speech)
> File "/data1/dtln/DTLN/DTLN_model.py", line 555, in train_model
> self.fs, train_flag=True)
> File "/data1/dtln/DTLN/DTLN_model.py", line 54, in **init**
> self.count_samples()
> File "/data1/dtln/DTLN/DTLN_model.py", line 68, in count_samples
> info = WavInfoReader(os.path.join(self.path_to_input, file))
> File "/root/.conda/envs/train_env/lib/python3.7/site-packages/wavinfo/wave_reader.py", line 52, in **init**
> self.main_list = chunks.children
> AttributeError: 'ChunkDescriptor' object has no attribute 'children'

@breizhn can you give some help about it?

**Comment by breizhn** [comment]
Hi @dttlgotv,

this sounds like, if the header of the audio/.wav files are not correct (more likely). Or they changed something in `wavinfo` (less likely). 
Can you load the .wav files with `soundfile`? 
Does the .wav files have correct content? 
How did you create your .wav files? 

If `soundfile` can read your data correctly, write a script to process your dataset and real file by file and write file by file again to disk with `soundfile`.

**Comment by dttlgotv** [comment]
> 
> 
> Hi @dttlgotv,
> 
> this sounds like, if the header of the audio/.wav files are not correct (more likely). Or they changed something in `wavinfo` (less likely).
> Can you load the .wav files with `soundfile`?
> Does the .wav files have correct content?
> How did you create your .wav files?
> 
> If `soundfile` can read your data correctly, write a script to process your dataset and real file by file and write file by file again to disk with `soundfile`.

You are right. I have to reinstal lfs again.
