### ISSUE TITLE
question about LSTM states

### ISSUE THREAD

**Issue by garrywrj** [breizhn/DTLN#24]
I'm trying to run your model on arm platform by TVM or any other inference engine. But there is nothing but tf-lite supported stateful LSTM.  From my experiment, I find that the model without states achieves a bad performance.
Is there any solution to achieve a good performance with stateless LSTM?
which mean:
model_1 = Model(inputs=mag, outputs=mask_1)
model_2 = Model(inputs=estimated_frame_1, outputs=decoded_frame)
I need your help

**Comment by breizhn** [comment]
Hi,

for a good performance you need the states. Without states you don't have any modelling/memory over time. You can try to implement the LSTM as multiple fully connected layers, but you need support of a concatenate operation and still have to pass the states of the last time step to the current one.

**Comment by liziru** [comment]
> You can try to implement the LSTM as multiple fully connected layers
Hi, 
I'm confused about ` You can try to implement the LSTM as multiple fully connected layers`. Do you mean I should replace LSTM with multiple fully connected layers and then concatenate the states of the last time step to the current input as a total input?  

Looking forward to your reply.

**Comment by breizhn** [comment]
An LSTM is basically one concatenation, four matrix multiplications and three dot products. So it can be implemented with fully connected layers, dot product operation and concatenate operation, when just one time step is calculated. For more on the theory of LSTMs see this wonderful blog post: https://colah.github.io/posts/2015-08-Understanding-LSTMs/
