### ISSUE TITLE
Model fails with exception if given epoch more than 62

### ISSUE THREAD

**Issue by pratistha** [breizhn/DTLN#25]
Hi, 

I'm trying to run your model on python 3.8.5 with the Tensorflow version of 2.3.1.
It works fine with lower epochs but as soon as it goes to 62 or higher epoch, the model fails with the exception given below 

2021-01-06 15:28:33.866558: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]

Have you faced such an error or can you tell what can be the solution for it?

Thanks in advance!

**Comment by breizhn** [comment]
Hi,

no actually I did not. I tested the repository with Tensorflow 2.2 and python 3.7 and I did not remember an error there. It is a bit strange that error occurs after a certain number of epochs. Normally when there is an error with the generator it should come up at the first epoch. Try to downgrade to 2.2, the performance should be similar. 

Did you change anything from the standard setup?
