### ISSUE TITLE
question about B1 model. 

### ISSUE THREAD

**Issue by liziru** [breizhn/DTLN#26]
Hi @breizhn, thanks for your job. 
I found the B1 model(4 Layer, STFT) in your paper. I understand there is only one separation kernel using an STFT analysis and synthesis basis and four LSTM layers in the B1 model( the second separation core is removed), and the training target is the negative SNR.  Do I understand correctly?

**Comment by breizhn** [comment]
Yes, this is correct!

**Comment by liziru** [comment]
> Yes, this is correct!

Thank you very much.
