### ISSUE TITLE
40h training early stopped between 80~90 epochs

### ISSUE THREAD

**Issue by guojunmin** [breizhn/DTLN#30]
Hi Nils,
Thank you for your great work! Recently I tried to train my model exactly  as you described in the environment created with train_env.yml, the only difference is my Ubuntu 20.04, however my training always early stopped between 80-90 epochs, val_loss -16~-17, no matter how I recreated dataset for training. Any suggestions to improve?
Thanks,
Junmin Guo

**Comment by breizhn** [comment]
Hi Junmin,

take random noise and speech file for each sample and mix them in a random SNR in the range between -5 and 25 dB SNR. Also create you data with 4s samples and train with a batchsize of 16. This should bring the performance a bit up and it should run for more epochs. It also recommended to vary the input level in good range. 

I don't when I manage to add that to this repo.

**Comment by guojunmin** [comment]
> Hi Junmin,
> 
> take random noise and speech file for each sample and mix them in a random SNR in the range between -5 and 25 dB SNR. Also create you data with 4s samples and train with a batchsize of 16. This should bring the performance a bit up and it should run for more epochs. It also recommended to vary the input level in good range.
> 
> I don't when I manage to add that to this repo.

Thanks a lot, I'll try your suggestions right away.

**Comment by guojunmin** [comment]
Hi Nils,

I tried 4s samples with a batchsize of 16, SNR is between -5 to 25 in the noisyspeech_synthesizer.cfg of your data repo, however I got errors as following,
Traceback (most recent call last):
  File "run_training.py", line 56, in <module>
    path_to_val_mix, path_to_val_speech)
  File "/home/junmin/DTLN/DTLN_model.py", line 580, in train_model
    use_multiprocessing=True)
  File "/home/junmin/anaconda3/envs/train_env/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/junmin/anaconda3/envs/train_env/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 856, in fit
    epoch_logs = copy.copy(logs)
UnboundLocalError: local variable 'logs' referenced before assignment

Then, I changed samples to 30s(default) and 15s, training stopped at epoch 72/75 with val_loss 16.9/15.9 respectively.

What's the normal epoch and val_loss in your training? I just want to repeat your training as the start point of my studying.

Thanks,
Junmin

**Comment by jeungmin717** [comment]
@guojunmin 
Hi,
How can you get val_loss around -11?
In my case I get over 40-46 val_loss
I didn't change a thing in this repository, or data configuration 500h (same as provided breizhn/dns-challenge) 
Can you give me some hint?

**Comment by steven8274** [comment]
> @guojunmin Hi, How can you get val_loss around -11? In my case I get over 40-46 val_loss I didn't change a thing in this repository, or data configuration 500h (same as provided breizhn/dns-challenge) Can you give me some hint?

Maybe you met the same problem of mine, you may refer to my post:https://github.com/breizhn/DTLN/issues/69

**Comment by steven8274** [comment]
> Hi Junmin,
> 
> take random noise and speech file for each sample and mix them in a random SNR in the range between -5 and 25 dB SNR. Also create you data with 4s samples and train with a batchsize of 16. This should bring the performance a bit up and it should run for more epochs. It also recommended to vary the input level in good range.
> 
> I don't when I manage to add that to this repo.

@breizhn Hi,Nils.Do you mean changing these two configs in DTLN_model.py?
```
        self.batchsize = 16
        self.len_samples = 4
```
since the SNR config in 'noisyspeech_synthesizer.cfg' is already '-5 and 25 dB'.

**Comment by steven8274** [comment]
> > Hi Junmin,
> > take random noise and speech file for each sample and mix them in a random SNR in the range between -5 and 25 dB SNR. Also create you data with 4s samples and train with a batchsize of 16. This should bring the performance a bit up and it should run for more epochs. It also recommended to vary the input level in good range.
> > I don't when I manage to add that to this repo.
> 
> @breizhn Hi,Nils.Do you mean changing these two configs in DTLN_model.py?
> 
> ```
>         self.batchsize = 16
>         self.len_samples = 4
> ```
> 
> since the SNR config in 'noisyspeech_synthesizer.cfg' is already '-5 and 25 dB'.

The training diverged after about 10 epochs when I use this config :(

**Comment by steven8274** [comment]
> > > Hi Junmin,
> > > take random noise and speech file for each sample and mix them in a random SNR in the range between -5 and 25 dB SNR. Also create you data with 4s samples and train with a batchsize of 16. This should bring the performance a bit up and it should run for more epochs. It also recommended to vary the input level in good range.
> > > I don't when I manage to add that to this repo.
> > 
> > 
> > @breizhn Hi,Nils.Do you mean changing these two configs in DTLN_model.py?
> > ```
> >         self.batchsize = 16
> >         self.len_samples = 4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > since the SNR config in 'noisyspeech_synthesizer.cfg' is already '-5 and 25 dB'.
> 
> The training diverged after about 10 epochs when I use this config :(

I found the reason of training stopped for 'NAN' is that the snr ratio value computed in 'snr_cost' function goes to zero, which make the 'log' function return 'NAN'.We should add an 'eps' , which is 1e-7, to the mean of square of signal.Then the ratio will no longer be zero anymore.
