### ISSUE TITLE
Modify to 32K sample rate

### ISSUE THREAD

**Issue by matt-audio** [breizhn/DTLN#42]
I tried to modified the DTLN model to 32K, but it always got error.
''----------------------------------------------------------------------------------------------------------------
File "/Library/Python/3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1110, in fit
    raise ValueError('Expect x to be a non-empty array or dataset.')
ValueError: Expect x to be a non-empty array or dataset.
''---------------------------------------------------------------------------------------------------------------

I changed the dataset to 32K, and  modify self.fs = 32000, and all fs related stuffs.

Please help...

**Comment by matt-audio** [comment]
I found the problem，Need to fix len_in_samples = 239872
but dont know why

**Comment by zqlsnr** [comment]
@matt-audio Hi，What is the noise reduction result of 32K model

**Comment by matt-audio** [comment]
Just the same as the 16K model can be used ...

**Comment by zqlsnr** [comment]
您好，您的32k model 实时处理的音频有嗡嗡声嘛？🥲 大概就是人说话的时候不清晰！

发自我的iPhone

**Comment by matt-audio** [comment]
有些情况下有，感觉跟数据集有关系。。
我目前也不知道是啥问题。。

________________________________

**Comment by zqlsnr** [comment]
hi，能否告诉您的32k 模型参数？
