### ISSUE TITLE
I'm training model 48K model, block_len and block_shift，encoder_size，numUnits ？

### ISSUE THREAD

**Issue by zqlsnr** [breizhn/DTLN#43]
Thanks for your wonderful job. @breizhn，48K model and 44.1K model，block_len and block_shift，encoder_size，numUnits, shouled I change these parameters?

**Comment by jeungmin717** [comment]
@zqlsnr have you found out any solution for training 48K model?

**Comment by ghost** [comment]
@jeungmin717 I modified the block_len and block_shift to train the DTLN B3 model, but the noise reduction performance is worse than the 16K model.

**Comment by jeungmin717** [comment]
@zqlsnr sorry for late reply,
does your 48k work ? curious about 48k model performance,, 
16k model is good enough but 48k isn't usable?
