### ISSUE TITLE
Real-time-processing Tf_lite inference program ERROR

### ISSUE THREAD

**Issue by cybermax-008** [breizhn/DTLN#5]
Hi I loaded a noisy one channel .wav file to perform inference using `real_time_processing_tf_lite.py`.
I got the following Dimension mismatch error. 

> Traceback (most recent call last):
>   File "real_time_processing_tf_lite.py", line 70, in <module>
>     interpreter_1.set_tensor(input_details_1[0]['index'], states_1)
>   File "/Users/cyberon/anaconda3/envs/dtln_py/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 399, in set_tensor
>     self._interpreter.SetTensor(tensor_index, value)
>   File "/Users/cyberon/anaconda3/envs/dtln_py/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 148, in SetTensor
>     return _interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
> ValueError: Cannot set tensor: Dimension mismatch. Got 4 but expected 3 for input 0.

Any inputs on this will be helpful!

**Comment by breizhn** [comment]
Should be fixed now.

**Comment by cybermax-008** [comment]
> Should be fixed now.

Thanks for the quick fix! 
The audio file is denoised finally.

**Comment by purnasai** [comment]
Hi, even after changing the input_details as you did in the file, the code is still giving an error 
```Traceback (most recent call last):
  File "real_time_processing_tf_lite.py", line 97, in <module>
    interpreter_2.set_tensor(input_details_2[0]['index'], estimated_block)#input_details_2[0]
  File "/home/purna/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 399, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
  File "/home/purna/.local/lib/python3.6/site-packages/tflite_runtime/interpreter_wrapper.py", line 148, in SetTensor
    return _interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 512 but expected 257 for dimension 2 of input 0.
```

**Comment by StuartIanNaylor** [comment]
@breizhn I just did the convert_weights_to_tf_lite.py then on a model I had just trained that is also default.
```
        self.fs = 16000
        self.batchsize = 32
        self.len_samples = 15
        self.activation = 'sigmoid'
        self.numUnits = 128
        self.numLayer = 2
        self.blockLen = 512
        self.block_shift = 128
        self.dropout = 0.25
        self.lr = 1e-3
        self.max_epochs = 200
        self.encoder_size = 256
        self.eps = 1e-7
```
Then run
```
python real_time_processing_tf_lite.py
Traceback (most recent call last):
  File "real_time_processing_tf_lite.py", line 69, in <module>
    interpreter_1.set_tensor(input_details_1[0]['index'], in_mag)
  File "/home/stuart/DTLN/venv/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 705, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 4 for input 0.
```
Its tflite_runtime 2.7.0 trained on 2.7.1 @breizhn Am I doing something wrong or have things regressed?

**Comment by abhinavchandel0** [comment]
@StuartIanNaylor I am facing the same issue. Please help me out if you have solved it.

**Comment by abhinavchandel0** [comment]
@breizhn

**Comment by StuartIanNaylor** [comment]
Nope apols haven't got round to trying yet.
