### ISSUE TITLE
Microphone sampling rate 

### ISSUE THREAD

**Issue by antreev-brar** [breizhn/DTLN#9]
I was trying to get `real_time_dtln_audio.py` to work . Should i change my microphone input and speaker output to 16khz as well ?

**Comment by breizhn** [comment]
It depends, coreAudio (MacOS) and PulseAudio (Linux) are accepting not native sampling rates as 16k. Whereby Alsa (Linux) can open audio devices just in the native sampling rate. When using Alsa, resampling must be integrated into the script. 

I don’t have any experience on the current Windows 10, but I think I remember from an old PortAudio project, that Wasapi also can use just the native/default sampling rate. But that was 5 years ago, maybe there was a change.
